---
task: "regression"
data_file: "subsevir/data/dataset_train.npz"
out_dir: "subsevir/models/cnn_regression"
yname: "y_regr"
metric_name: "r2"
models:
  - "0"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
n_train_samples: "60000"
channels: 
  - "0"
  - "0,1,2"
img_scales:
  - "1"
  - "2"
  - "3"
filter_widths:
  - "4"
  - "8"
  - "12"
patch_sizes: "1,2,4,6,8,16,28"
learning_rate: "0.005"
epochs: 250
