---
task: "regression"
data_file: "tornado/data/dataset.npz"
out_dir: "tornado/models/cnn_regression"
yname: "y_regr"
metric_name: "r2"
models:
  - "0"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
n_train_samples: "25000"
channels: 
  - "0"
    #  - "0,1,2"
img_scales:
   - "0.5"
   - "1"
   - "2"
   - "3"
filter_widths:
  - "4"
  - "8"
  - "12"
group_method: "grid"
patch_sizes: "1,2,4,8,16,32"
learning_rate: "0.0005"
epochs: 100
